# .github/workflows/github-release-publish.yml
name: Publish artifacts to github release

on:
  release:
    types: [published]

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    permissions:
      id-token: write # To sign.
      contents: write # To upload release assets.
      actions: read   # To read workflow path.
    strategy:
      fail-fast: false
      matrix:
        goos: [linux, darwin]
        goarch: [amd64, arm64]
    steps:
      - uses: actions/checkout@v4
      - uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          binary_name: "pubsub-sub-bench"
          sha256sum: true
          asset_name: pubsub-sub-bench-${{ matrix.goos }}-${{ matrix.goarch }}
          build_command: "make build"
          retry: 5
          overwrite: true

  docker-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch full history for Git info

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract Git metadata
      id: meta
      run: |
        GIT_SHA=$(git rev-parse HEAD)
        GIT_DIRTY=$(git diff --no-ext-diff 2>/dev/null | wc -l)
        echo "git_sha=${GIT_SHA}" >> $GITHUB_OUTPUT
        echo "git_dirty=${GIT_DIRTY}" >> $GITHUB_OUTPUT

    - name: Extract metadata for Docker
      id: docker_meta
      uses: docker/metadata-action@v5
      with:
        images: filipe958/pubsub-sub-bench
        tags: |
          type=ref,event=tag
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ steps.docker_meta.outputs.tags }}
        labels: ${{ steps.docker_meta.outputs.labels }}
        build-args: |
          GIT_SHA=${{ steps.meta.outputs.git_sha }}
          GIT_DIRTY=${{ steps.meta.outputs.git_dirty }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
